language: node_js
node_js:
  - 'node'

cache: npm

script: npm run build

os:
  - 'linux'

dist: xenial

deploy:
  provider: pages
  strategy: git
  token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: master
